<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Fiap.CloudGames.Audit.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.404.10" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.300" />
    <PackageReference Include="MassTransit" Version="8.5.7" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fiap.CloudGames.Audit.Application\Fiap.CloudGames.Audit.Application.csproj" />
    <ProjectReference Include="..\Fiap.CloudGames.Audit.Domain\Fiap.CloudGames.Audit.Domain.csproj" />
  </ItemGroup>

</Project>
